
services:
    server:
        build: 
            context: "./server"
            dockerfile: "Dockerfile"
        ports: 
            - "8081:8081"
        volumes: 
            - "./server/:/home/app"
            - "./server/node_modules/:/home/app/node_modules"
    
    app:
        build:
            context: "./app"
            dockerfile: "Dockerfile"
        ports: 
            - "80:3000"
        volumes: 
            - "./app:/home/app"
            - "./app/node_modules/:/home/app/node_modules"
